### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by Kerblif** [fluttercommunity/chewie#645]
I want to play hls in web, but it's not working

```
TypeError: Cannot read properties of undefined (reading 'isSupported')
    at video_player_web_hls._VideoPlayer.new.initialize (http://localhost:57203/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:372:29)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:57203/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:57203/dart_sdk.js:40691:7)
    at video_player_web_hls._VideoPlayer.new.initialize (http://localhost:57203/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:358:20)
    at video_player_web_hls.VideoPlayerPluginHls.new.create (http://localhost:57203/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:228:22)
    at create.next (<anonymous>)
    at runBody (http://localhost:57203/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:57203/dart_sdk.js:40691:7)
    at video_player_web_hls.VideoPlayerPluginHls.new.create (http://localhost:57203/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:186:20)
    at video_player.VideoPlayerController.network.initialize (http://localhost:57203/packages/video_player/video_player.dart.lib.js:817:76)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:57203/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:57203/dart_sdk.js:40691:7)
    at video_player.VideoPlayerController.network.initialize (http://localhost:57203/packages/video_player/video_player.dart.lib.js:772:20)
    at chewie_player.ChewieController.new._initialize (http://localhost:57203/packages/chewie/src/material/material_controls.dart.lib.js:5149:44)
    at _initialize.next (<anonymous>)
    at http://localhost:57203/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:57203/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:57203/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:57203/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:57203/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:57203/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57203/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:57203/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:57203/dart_sdk.js:40784:13)
    at http://localhost:57203/dart_sdk.js:36261:9
```

My code:
```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:chewie/chewie.dart';
import 'dart:async';
import 'Utils/UnprismAPI.dart';

class MyVideoPlayer extends StatefulWidget {
  final String contentURL;
  final String epTag;
  final String movieId;

  const MyVideoPlayer(
      {Key? key,
      required this.contentURL,
      required this.epTag,
      required this.movieId})
      : super(key: key);

  @override
  State<MyVideoPlayer> createState() => _MyVideoPlayerState(
      contentURL: contentURL, epTag: epTag, movieId: movieId);
}

class _MyVideoPlayerState extends State<MyVideoPlayer> {
  final String contentURL;
  final String epTag;
  final String movieId;

  _MyVideoPlayerState(
      {required this.contentURL, required this.epTag, required this.movieId});

  late VideoPlayerController _controller;
  late ChewieController _chewieController;
  late Chewie _videoWidget;
  late Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    super.initState();

    _controller = VideoPlayerController.network(contentURL);
    _initializeVideoPlayerFuture = _controller.initialize();

    user().getTimestamps(movieId).then((Result value) {
      try {
        int times = int.parse(value.Data[epTag]);

        _controller.seekTo(Duration(seconds: times));
      } catch (e) {
        _controller.seekTo(const Duration(seconds: 0));
      }
      // _controller.seekTo();
    });

    _chewieController = ChewieController(
      videoPlayerController: _controller,
      autoPlay: true,
      looping: false,
    );

    _videoWidget = Chewie(
      controller: _chewieController,
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    _chewieController.dispose();
    super.dispose();
  }

  late Duration _curTime;

  @override
  Widget build(BuildContext context) {
    var playerScreen = Scaffold(
        appBar: AppBar(
            title: const Text("Player"), automaticallyImplyLeading: false),
        body: Center(
            child: Column(children: [
          FutureBuilder(
            future: _initializeVideoPlayerFuture,
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.done) {
                return AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: _videoWidget);
              } else {
                return const Center(
                  child: CircularProgressIndicator(),
                );
              }
            },
          )
        ])));

    return playerScreen;
  }
}
```

What did I do wrong?

**Comment by Kerblif** [comment]
Even that doesn't work:

```
import 'package:flutter/material.dart';
import 'package:chewie/chewie.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final videoPlayerController = VideoPlayerController.network(
      'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8');
  late ChewieController chewieController;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    chewieController = ChewieController(
      videoPlayerController: videoPlayerController,
      aspectRatio: 3 / 2,
      looping: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Sample App"),
        ),
        body: Container(
          child: Chewie(controller: chewieController),
        ));
  }
}
```

**Comment by Kerblif** [comment]
If I change url from
`'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8'`
to
`'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4'`
it's working.

**Comment by Kerblif** [comment]
Strange - the problem was solved by simply uploading the site to netlify. Probably
`python -m http.server --bind 127.0.0.1`
just not suitable for the site?
