### ISSUE TITLE
HELP: Unhandled Exception: UnimplementedError: init() has not been implemented

### ISSUE THREAD

**Issue by lixiang4u** [fluttercommunity/chewie#693]
## env:
flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (5 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

## os:
OS: macOS 12.5.1 21G83 arm64 
Host: MacBookPro17,1 
Kernel: 21.6.0 
Uptime: 21 days, 1 hour, 40 mins 
Packages: 125 (brew) 
Shell: zsh 5.8.1 
Resolution: 1680x1050 
DE: Aqua 
WM: Quartz Compositor 
WM Theme: Blue (Light) 
Terminal: Apple_Terminal 
Terminal Font: Monaco 
CPU: Apple M1 
GPU: Apple M1 
Memory: 3260MiB / 16384MiB 

### i copy code from [https://medium.flutterdevs.com/video-player-in-flutter-22202be72d6e](https://medium.flutterdevs.com/video-player-in-flutter-22202be72d6e)
```code
// video_items.dart

import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoItems extends StatefulWidget {
  final VideoPlayerController videoPlayerController;
  final bool looping;
  final bool autoplay;

  VideoItems({
    required this.videoPlayerController,
    required this.looping,
    required this.autoplay,
    Key? key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _VideoItemsState();
}

class _VideoItemsState extends State<VideoItems> {
  late ChewieController _chewieController;

  @override
  void initState() {
    super.initState();
    _chewieController = ChewieController(
      videoPlayerController: widget.videoPlayerController,
      aspectRatio: 5 / 8,
      autoInitialize: true,
      autoPlay: widget.autoplay,
      looping: widget.looping,
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Chewie(
        controller: _chewieController,
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _chewieController.dispose();
  }
}


```

```code
// chewie_test.dart

import 'package:flutter/material.dart';
import 'package:github_app/components/video/video_items.dart';
import 'package:video_player/video_player.dart';

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blueGrey[100],
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: Text('Flutter Video Player Demo'),
        centerTitle: true,
      ),
      body: ListView(
        children: <Widget>[
          // VideoItems(
          //   videoPlayerController: VideoPlayerController.asset(
          //     'assets/video_6.mp4',
          //   ),
          //   looping: true,
          //   autoplay: true,
          // ),
          VideoItems(
            videoPlayerController: VideoPlayerController.network(
                'https://assets.mixkit.co/videos/preview/mixkit-a-girl-blowing-a-bubble-gum-at-an-amusement-park-1226-large.mp4'),
            looping: false,
            autoplay: true,
          ),
          // VideoItems(
          //   videoPlayerController: VideoPlayerController.asset(
          //     'assets/video_3.mp4',
          //   ),
          //   looping: false,
          //   autoplay: false,
          // ),
          // VideoItems(
          //   videoPlayerController: VideoPlayerController.asset(
          //     'assets/video_2.mp4',
          //   ),
          //   autoplay: true,
          //   looping: false,
          // ),
          VideoItems(
            videoPlayerController: VideoPlayerController.network(
                "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"),
            looping: true,
            autoplay: false,
          ),
        ],
      ),
    );
  }
}

```

## result
```code
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:362:25)
#3      ChewieController._initialize (package:chewie/src/chewie_player.dart:552:35)
<asynchronous suspension>

```

is chewie do not support macos or something other wrong?
 
i was reinstall `video_player` and `chewie` package,and still not working .

```code
flutter pub remove chewie 
flutter pub remove video_player
flutter pub add video_player
flutter pub add chewie
```

**Comment by lixiang4u** [comment]
may flutter framework issue, or my env broken.
i use `video_player` package was show this error again.

```code
An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:52907/H4she_gsJE4=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:362:25)
#3      _VideoAppState.initState (package:github_app/main.dart:22:9)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#14     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
#15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

```

**Comment by jhielson** [comment]
Hi,

I got here the same error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: init() has not been implemented.
#0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:28:21)
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:362:25)
#3      _MaterialDesktopControlsState._playPause.<anonymous closure> (package:chewie/src/material/material_desktop_controls.dart:511:22)
#4      State.setState (package:flutter/src/widgets/framework.dart:1114:30)
#5      _MaterialDesktopControlsState._playPause (package:chewie/src/material/material_desktop_controls.dart:502:5)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#19     _invoke1 (dart:ui/hooks.dart:167:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
```
Any solution?

**Comment by Sherlock-Holo** [comment]
got this problem too

**Comment by ahetawal-p** [comment]
I have started seeing this problem as well Flutter 3.7.0

**Comment by diegotori** [comment]
@jhielson based on the provided stack trace, the problem lies in `video_player`, which `chewie` makes use of, but does not control.

As a result, please file an issue inside the Flutter Project's GitHub page for further help.

**Comment by sapar-io** [comment]
Same error. Any solution?
