### ISSUE TITLE
Unable to Play large file video from Google Drive Link

### ISSUE THREAD

**Issue by amuchand47** [fluttercommunity/chewie#714]
I am trying to play a video from a google drive link, the video is more than 300 MB, so getting a warning itself to download it anyway from the link when I open it in the browser. So I just want to play the video bypassing the message **download it anyway from the link**

But getting errors like this:

`
I/ExoPlayerImpl(28303): Release da45690 [ExoPlayerLib/2.18.1] [sakura_india, Redmi 6 Pro, Xiaomi, 28] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/ExoPlayerImpl(28303): Init b6c8f9 [ExoPlayerLib/2.18.1] [sakura_india, Redmi 6 Pro, Xiaomi, 28]
D/AudioManager(28303): getStreamVolume isRestricted mode = 0
E/ExoPlayerImplInternal(28303): Playback error
E/ExoPlayerImplInternal(28303):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(28303):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(28303):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
E/ExoPlayerImplInternal(28303):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(28303):       at android.os.Looper.loop(Looper.java:201)
E/ExoPlayerImplInternal(28303):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(28303):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(28303):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(28303):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
E/ExoPlayerImplInternal(28303):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(28303):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(28303):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(28303):       at java.lang.Thread.run(Thread.java:764)
E/flutter (28303): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (28303): 
`

Please help me out, I am not pretty sure that  this error is because of google warning **download it anyway from the link**

**Comment by hossameldinmi** [comment]
Any update?
