### ISSUE TITLE
Out of memory error with specific video

### ISSUE THREAD

**Issue by JohnWeidner** [fluttercommunity/chewie#716]
I just noticed an out-of-memory error happening when I tried to play this particular video:

https://imgprd21.museumofthebible.org/mobileapi/media/0a587643-9fd9-4869-a037-e5cf34bab99a.mp4

I saw the issue with with 1.3.6 and 1.4.0.  However, if I switch back to using the 1.3.5 version of the Chewie plugin the OOM error does not happen.

**Comment by aneeshjoshi** [comment]
I received the error on 1.3.5 as well. Not sure if your error was the same one @JohnWeidner 

`E/ExoPlayerImplInternal(17875): Playback error
E/ExoPlayerImplInternal(17875):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
E/ExoPlayerImplInternal(17875):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(17875):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(17875):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(17875):   Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 34760 byte allocation with 0 free bytes and 0B until OOM, target footprint 201328032, growth limit 201326592
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
E/ExoPlayerImplInternal(17875):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(17875):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(17875):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal(17875):   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 34760 byte allocation with 0 free bytes and 0B until OOM, target footprint 201328032, growth limit 201326592
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:478)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:150)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:515)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:474)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:456)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:254)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
E/ExoPlayerImplInternal(17875):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(17875):       ... 3 more
`

**Comment by diegotori** [comment]
@JohnWeidner this is definitely a `video_player` issue affecting the underlying library that this one uses.

Please raise this issue with the Flutter team.
